- models: [ "A30" ]
  allowedGeometries:
    - 1g.6gb: 4
    - 1g.6gb: 2
      2g.12gb: 1
    - 2g.12gb: 2
    - 4g.24gb: 1
- models: [ "A100-SXM4-40GB", "NVIDIA-A100-40GB-PCIe", "NVIDIA-A100-SXM4-40GB"]
  allowedGeometries:
    - 1g.5gb: 7
    - 1g.5gb: 5
      2g.10gb: 1
    - 1g.5gb: 3
      2g.10gb: 2
    - 1g.5gb: 1
      2g.10gb: 3
    - 1g.5gb: 2
      2g.10gb: 1
      3g.20gb: 1
    - 2g.10gb: 2
      3g.20gb: 1
    - 1g.5gb: 3
      3g.20gb: 1
    - 1g.5gb: 1
      2g.10gb: 1
      3g.20gb: 1
    - 3g.20gb: 2
    - 1g.5gb: 3
      4g.20gb: 1
    - 1g.5gb: 1
      2g.10gb: 1
      4g.20gb: 1
    - 7g.40gb: 1
- models: [ "NVIDIA-A100-SXM4-80GB", "NVIDIA-A100-80GB-PCIe", "NVIDIA-H100-PCIe", "NVIDIA-H100-80GB"]
  allowedGeometries:
    - 1g.10gb: 7
    - 1g.10gb: 5
      2g.20gb: 1
    - 1g.10gb: 3
      2g.20gb: 2
    - 1g.10gb: 1
      2g.20gb: 3
    - 1g.10gb: 2
      2g.20gb: 1
      3g.40gb: 1
    - 2g.20gb: 2
      3g.20gb: 1
    - 1g.10gb: 3
      3g.40gb: 1
    - 1g.10gb: 1
      2g.20gb: 1
      3g.40gb: 1
    - 3g.40gb: 2
    - 1g.10gb: 3
      4g.40gb: 1
    - 1g.10gb: 1
      2g.20gb: 1
      4g.40gb: 1
    - 7g.79gb: 1
