resources:
- gpu_partitioner.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - gpu_partitioner_config.yaml
  name: gpu-partitioner-config
- files:
  - known_mig_geometries.yaml
  name: gpu-partitioner-known-mig-geometries

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: gpu-partitioner
  newName: ghcr.io/saguirregaray1/nos-gpu-partitioner
  newTag: 0.0.1
