---

apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-info-exporter
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: cluster-info-exporter
spec:
  selector:
    matchLabels:
      name: cluster-info-exporter
      app.kubernetes.io/component: cluster-info-exporter
  template:
    metadata:
      labels:
        name: cluster-info-exporter
        app.kubernetes.io/component: cluster-info-exporter
    spec:
      serviceAccountName: cluster-info-exporter
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 30
      containers:
        - name: cluster-info-exporter
          image: cluster-info-exporter:latest
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(ENDPOINT)
            - --interval=$(INTERVAL)
            - --http-timeout=$(HTTP_TIMEOUT)
            - --api-token=$(API_TOKEN)
          env:
            - name: ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: cluster-info-exporter-config
                  key: endpoint
            - name: INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: cluster-info-exporter-config
                  key: interval
            - name: HTTP_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: cluster-info-exporter-config
                  key: httpTimeout
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cluster-info-exporter-secrets
                  key: apiToken
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
